tasks:
- parallel:
    - mixed_system_test.rgw_ios:
        test: test_acls
        test_version: v1
        clients: ['client.0']
    - mixed_system_test.rgw_ios:
        test: test_acls_all_usrs
        test_version: v1
        clients: ['client.1']
    - mixed_system_test.rgw_ios:
        test: test_acls_copy_obj
        test_version: v1
        clients: ['client.0']
    - mixed_system_test.rgw_ios:
        test: test_acls_reset
        test_version: v1
        clients: ['client.1']
    - mixed_system_test.rgw_ios:
        test: test_multipart_upload_cancel
        test_version: v1
        clients: ['client.0']
    - mixed_system_test.rgw_ios:
        test: Mbuckets_with_Nobjects_Sharding
        script: test_Mbuckets_with_Nobjects.py
        clients: ['client.1']
        config:
            local_file_delete: true
            user_count: 2
            bucket_count: 5
            objects_count: 100
            objects_size_range:
                min: 100
                max: 200
            test_ops:
                create_bucket: true
                create_object: true
                download_object: true
                delete_bucket_object: true
                sharding:
                    enable: true
                    max_shards: 32
                compression:
                    enable: false
                    type: zlib
- parallel:
    - mixed_system_test.rgw_ios:
        test: Mbuckets_with_Nobjects
        script: test_Mbuckets_with_Nobjects.py
        clients: ['client.0']
        config:
            local_file_delete: true
            user_count: 5
            bucket_count: 5
            objects_count: 50
            objects_size_range:
                min: 100
                max: 200
            test_ops:
                create_bucket: true
                create_object: true
                download_object: true
                delete_bucket_object: true
                sharding:
                    enable: false
                    max_shards: 0
                compression:
                    enable: false
                    type: zlib
    - mixed_system_test.rgw_ios:
        test: Mbuckets_with_Nobjects_multipart
        script: test_Mbuckets_with_Nobjects.py
        clients: ['client.1']
        config:
            local_file_delete: true
            user_count: 2
            bucket_count: 5
            objects_count: 50
            objects_size_range:
                min: 1000
                max: 1500
            test_ops:
                create_bucket: true
                create_object: true
                download_object: true
                delete_bucket_object: true
                upload_type: multipart
                sharding:
                    enable: false
                    max_shards: 0
                compression:
                    enable: false
                    type: zlib
    - mixed_system_test.rgw_ios:
        test: versioning_ops
        script: test_versioning_with_objects.py
        clients: ['client.0']
        config:
            local_file_delete: true
            user_count: 2
            bucket_count: 2
            objects_count: 50
            version_count: 5
            objects_size_range:
                min: 50
                max: 80
            test_ops:
                enable_version: true
                suspend_version: true
                copy_to_version: false
                delete_object_versions: false
                upload_after_suspend: true
    - mixed_system_test.rgw_ios:
        test: versioning_ops_delete
        script: test_versioning_with_objects.py
        clients: ['client.1']
        config:
            local_file_delete: true
            user_count: 2
            bucket_count: 2
            objects_count: 50
            version_count: 5
            objects_size_range:
                min: 50
                max: 80
            test_ops:
                enable_version: true
                suspend_version: false
                copy_to_version: false
                delete_object_versions: true
                upload_after_suspend: false
    - mixed_system_test.restart_tests:
        daemons: ["mgr", "mon", "mds", "osd"]

