tasks:
- parallel:
    - mixed_system_test.rgw_ios:
        test: Lifecycle_ops_expiration_date
        script: test_bucket_lifecycle_object_expiration.py
        clients: ['client.0']
        config:
          user_count: 1
          bucket_count: 1
          objects_count: 2000
          objects_size_range:
            min: 5K
            max: 10K
          test_ops:
            enable_versioning: true
            create_object: true
            version_count: 3
            delete_marker: false
          lifecycle_conf:
            - ID: LC_Rule_1
              Filter:
                Prefix: key1
              Status: Enabled
              Expiration:
                Date: '2019-02-17'
    - mixed_system_test.rgw_ios:
        test: Life_cycle_ops_expiration_days_delete_marker_rule
        script: test_bucket_lifecycle_object_expiration.py
        clients: ['client.1']
        config:
          user_count: 1
          bucket_count: 1
          objects_count: 2000
          objects_size_range:
            min: 5K
            max: 10K
          test_ops:
            enable_versioning: true
            create_object: true
            version_count: 3
            delete_marker: false
          lifecycle_conf:
            - ID: LC_Rule_1
              Filter:
                Prefix: key2
              Status: Enabled
              Expiration:
                Days: 2
          delete_marker_ops:
            - ID: delete_marker_rule
              Filter:
                Prefix: key2
              Status: Enabled
              Expiration:
                ExpiredObjectDeleteMarker: true
    - mixed_system_test.rgw_ios:
        test: Lifecycle_ops_expiration_days_multiple_lc_rules
        script: test_bucket_lifecycle_object_expiration.py
        clients: ['client.0']
        config:
          user_count: 1
          bucket_count: 1
          objects_count: 2000
          objects_size_range:
            min: 5K
            max: 10K
          test_ops:
            enable_versioning: true
            create_object: true
            version_count: 3
            delete_marker: false
          lifecycle_conf:
            - ID: LC_Rule_1
              Filter:
                Prefix: key1
              Status: Enabled
              Expiration:
                Days: 2
            - ID: LC_Rule_2
              Filter:
                Prefix: key2
              Status: Enabled
              Expiration:
                Days: 2
    - mixed_system_test.rgw_ios:
        test: Lifecycle_ops_expiration_days_prefix_tags
        script: test_bucket_lifecycle_object_expiration.py
        clients: ['client.1']
        config:
          user_count: 1
          bucket_count: 1
          objects_count: 2000
          objects_size_range:
            min: 5K
            max: 10K
          test_ops:
            enable_versioning: false
            create_object: true
            delete_marker: false
            version_count: 0
          lifecycle_conf:
            - ID: rule1
              Filter:
                And:
                  Prefix: key1
                  Tags:
                    - Key: suffix1
                      Value: WMV1
              Status: Enabled
              Expiration:
                Days: 2
    - mixed_system_test.rgw_ios:
        test: Lifecycle_ops_non_current_expiration_days
        script: test_bucket_lifecycle_object_expiration.py
        clients: ['client.0']
        config:
          user_count: 1
          bucket_count: 1
          objects_count: 1
          objects_size_range:
            min: 5K
            max: 15K
          test_ops:
            enable_versioning: true
            create_object: true
            version_count: 3
            delete_marker: false
          lifecycle_conf:
            - ID: LC_Rule_2
              Filter:
                Prefix: key1
              Status: Enabled
              NoncurrentVersionExpiration:
                NoncurrentDays: 2

