tasks:
- parallel:
    - mixed_system_test.rgw_ios:
        test: test_gc_list
        script: test_Mbuckets_with_Nobjects.py
        clients: ['client.0']
        config:
          user_count: 1
          bucket_count: 1
          objects_count: 1000000
          gc_verification: true
          local_file_delete: true
          ceph_conf:
            bluestore_block_size: 1549267441664
            rgw_gc_max_queue_size: 367788
            rgw_gc_processor_max_time: 3600
            rgw_gc_max_concurrent_io: 10
            rgw_objexp_gc_interval: 10
            rgw_gc_max_trim_chunk: 32
            rgw_gc_obj_min_wait: 10
            rgw_gc_processor_period: 10
          objects_size_range:
            min: 5K
            max: 10K
          test_ops:
            create_bucket: true
            create_object: true
            download_object: false
            delete_bucket_object: true
            sharding:
              enable: false
              max_shards: 0
            compression:
              enable: false
              type: zlib
