# tests s3 objects upload, download and deleting of buckets and objects
# multipart upload
tasks:
  - ssh-keys: null
  - install.ship_utilities:
  - rhceph_ansible: null
  - rgw-longrunning:
      test: Mbuckets_with_Nobjects_multipart
      script: test_Mbuckets_with_Nobjects.py
      config:
        user_count: 2
        bucket_count: 2
        size_ranges: [50, 100, 250, 500, 1000]
        local_file_delete: true
        test_ops:
          create_bucket: true
          create_object: true
          download_object: true
          delete_bucket_object: true
          upload_type: multipart
          sharding:
            enable: false
            max_shards: 0
          compression:
            enable: false
            type: zlib