tasks:
  - ssh-keys: null
  - install.ship_utilities:
  - rhceph_ansible: null
  - rgw-system-test:
      test: Mbuckets_with_Nobjects_multipart
      script: test_Mbuckets_with_Nobjects.py
      clients: ['client.0']
      config:
        user_count: 2
        bucket_count: 5
        objects_count: 10
        objects_size_range:
          min: 1000
          max: 1500
        test_ops:
          create_bucket: true
          create_object: true
          download_object: true
          delete_bucket_object: true
          upload_type: multipart
          sharding:
            enable: false
            max_shards: 0
          compression:
            enable: false
            type: zlib