tasks:
  - ssh-keys: null
  - install.ship_utilities:
  - rhceph_ansible: null
  - rgw-system-test:
      test: versioning_ops
      script: test_versioning_with_objects.py
      clients: ['client.0']
      config:
        user_count: 2
        bucket_count: 2
        objects_count: 10
        version_count: 5
        objects_size_range:
          min: 50
          max: 80
        test_ops:
          enable_version: true
          suspend_version: false
          copy_to_version: false
          delete_object_versions: true
          upload_after_suspend: false