tasks:
- ssh-keys: null
- install.ship_utilities: null
- rhceph_ansible:
    cluster: c1
- rhceph_ansible:
    cluster: c2
- new_rgw_multisite:
   realm:
     name: test-realm
     is_default: true
   zonegroups:
     - name: test-zg
       is_master: true
       is_default: true
       zones:
         - name: test-zone
           is_master: true
           is_default: true
           endpoints: [c1.rgw.0]
         - name: test-zone2
           is_default: true
           endpoints: [c2.rgw.1]
- netem:
    clients: [c1.rgw.0]
    iface: eno1
    dst_client: c2.rgw.1
    delay_range: [30ms, 100ms]
- multisite-test.userexec:
      master_client: c1.rgw.0
      test_dir_version: v1
      master_config:
        user_count: 3
- sleep:
   duration: 60
- ceph-ipmi.poweroff: [c2.rgw.1]
- multisite-test:
      test_client: c1.rgw.0
      target_config:
        bucket_count: 2
        objects_count: 10
        max_file_size: 10
        min_file_size: 5
      test-name: test_Mbuckets_with_Nobjects
      test_dir_version: v1
- ceph-ipmi.poweron: [c2.rgw.1]
- sleep:
   duration: 60
- multisite-test.pull-io-info:
- verify-io:
      verification_script: read_io_info
